# Generated by Django 4.2.6 on 2023-10-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
