# Generated by Django 4.2.6 on 2023-10-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_sponsor_is_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='is_legal',
        ),
    ]
